server:
  port: 8888  

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sambitc/mm-sample-config
  
eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST}:8761/eureka/