--- 
configserver:
  image: mm/configserver-ms
  restart: always
  environment:
    - SERVICE_REGISTRY_HOST: ${MYAPP_STAGING_IP}
  links:
    - discovery
  ports:
    - "8888:8888"

discovery:
  image: mm/discovery-ms
  restart: always
  ports:
    - "8761:8761"

playlist-history:
  image: mm/playlist-history-ms
  restart: always
  environment:
    - SERVICE_REGISTRY_HOST: ${MYAPP_STAGING_IP}
    - CONFIG_SERVER_HOST: ${MYAPP_STAGING_IP}
    - DB_HOST: ${MYAPP_STAGING_IP}
  links:
    - configserver
    - discovery

playlist-song:
  image: mm/playlist-song-ms
  restart: always
  environment:
    - SERVICE_REGISTRY_HOST: ${MYAPP_STAGING_IP}
    - CONFIG_SERVER_HOST: ${MYAPP_STAGING_IP}
    - DB_HOST: ${MYAPP_STAGING_IP}
  links:
    - configserver
    - discovery

playlist-api:
  image: mm/playlist-api-ms
  restart: always
  environment:
    - SERVICE_REGISTRY_HOST: ${MYAPP_STAGING_IP}
    - CONFIG_SERVER_HOST: ${MYAPP_STAGING_IP}
  ports:
    - "8091:8091"
  links:
    - configserver
    - discovery
    - playlist-history
    - playlist-song
 

